name: supabase_demo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.9.0
  flutter_dotenv: ^5.0.2
  sign_in_with_apple: ^7.0.1
  file_picker: ^10.2.0
  path: ^1.9.1
  http: ^1.1.0
  flutter_html: ^3.0.0-beta.2 # Or latest stable version
  share_plus: ^11.0.0      # Use latest version
  url_launcher: ^6.1.7
  fl_chart: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/recipe_placeholder.png
